version: 2
jobs:
  eslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cp .eslintrc ./logdna/.eslintrc
      - run: cd ./logdna && npm install .
      - run: cd ./logdna && npm run lint
      - run: cd ./logdna && npm test
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            TAG_VERSION=$(git tag --sort=-creatordate | head -n 1)
            PKG_VERSION=$(cat ./logdna/package.json | grep version | cut -d':' -f2 | cut -d '"' -f2)
            if [[ "${TAG_VERSION}" != "${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${TAG_VERSION}"
              echo "  PKG_VERSION: ${PKG_VERSION}"
              exit 1
            fi
            echo ${TAG_VERSION} >> ./logdna/VERSION.txt
      - run:
          name: Build CloudWatchLogs
          command: |
            cd ./logdna && rm -rf node_modules
            cd ./logdna && npm install --production
            zip logdna-cloudwatch.zip -r node_modules/ index.js package.json
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna/logdna-cloudwatch.zip
            - ./logdna/VERSION.txt
  publish:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run:
          name: Upload into S3
          command: |
            aws s3 cp ./logdna/logdna-cloudwatch.zip s3://repo.logdna.com/integrations/lambdas/logdna-cloudwatch.zip
            aws s3 cp ./logdna/logdna-cloudwatch.zip s3://repo.logdna.com/integrations/lambdas/logdna-cloudwatch.$(cat ./logdna/VERSION.txt).zip
workflows:
  version: 2
  update:
    jobs:
      - eslint:
          filters:
            tags:
              only: /[0-9].[0-9].[0-9]/
            branches:
              ignore: /.*/
      - build:
          requires:
            - eslint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].[0-9].[0-9]/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].[0-9].[0-9]/
  eslint:
    jobs:
      - eslint:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
