version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Build CloudWatchLogs
          command: |
            cd ./src && npm install .
            zip logdna_cloudwatchlogs.zip -r node_modules/ index.js
      - persist_to_workspace:
          root: .
          paths:
            - ./src/logdna_cloudwatchlogs.zip
  publish:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run: aws s3 cp ./src/logdna_cloudwatchlogs.zip s3://repo.logdna.com/integrations/lambdas/logdna_cloudwatchlogs.zip
workflows:
  version: 2
  update:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]{10}$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]{10}$/
