version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            TAG_VERSION=$(git tag --sort=-creatordate | head -n 1)
            PKG_VERSION=$(cat package.json | grep version | cut -d':' -f2 | cut -d '"' -f2)
            if [[ "${TAG_VERSION}" != "${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${TAG_VERSION}"
              echo "  PKG_VERSION: ${PKG_VERSION}"
              exit 1
            fi
            echo ${TAG_VERSION} >> ./logdna/VERSION.txt
      - run:
          name: Build CloudWatchLogs
          command: |
            cd ./logdna && npm install .
            zip logdna_cloudwatchlogs.zip -r node_modules/ index.js
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna/logdna_cloudwatchlogs.zip
            - ./logdna/VERSION.txt
  publish:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run:
          name: Upload into S3
          command: |
            aws s3 cp ./logdna/logdna_cloudwatchlogs.zip s3://repo.logdna.com/integrations/lambdas/logdna_cloudwatchlogs.zip
            aws s3 cp ./logdna/logdna_cloudwatchlogs.zip s3://repo.logdna.com/integrations/lambdas/logdna_cloudwatchlogs.$(cat ./src/VERSION.txt).zip
workflows:
  version: 2
  update:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
